// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZg-GHbFT_V0aagYQpld4STiic2iOZwAA',
    appId: '1:1095225439242:web:f8fc6f8c4d7a50700e9bf3',
    messagingSenderId: '1095225439242',
    projectId: 'shoebot-cd8ad',
    authDomain: 'shoebot-cd8ad.firebaseapp.com',
    storageBucket: 'shoebot-cd8ad.appspot.com',
    measurementId: 'G-2Q885628FD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMDM6IZN0hXfo1S4ZJvg_Fh6Dakcs_lyE',
    appId: '1:1095225439242:android:e7f92968252cc00f0e9bf3',
    messagingSenderId: '1095225439242',
    projectId: 'shoebot-cd8ad',
    storageBucket: 'shoebot-cd8ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpurV3nsTDaZFAmK60kaO7LIsKZODwXZA',
    appId: '1:1095225439242:ios:22a3f46478ff4cbf0e9bf3',
    messagingSenderId: '1095225439242',
    projectId: 'shoebot-cd8ad',
    storageBucket: 'shoebot-cd8ad.appspot.com',
    androidClientId: '1095225439242-co4vkk3ra8bf5m0b89gm9iqnk6ka0dsg.apps.googleusercontent.com',
    iosClientId: '1095225439242-lgrpu243u0ic6ovsd1l2stn15q5kvnkj.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoebot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpurV3nsTDaZFAmK60kaO7LIsKZODwXZA',
    appId: '1:1095225439242:ios:335726d2f420b7ca0e9bf3',
    messagingSenderId: '1095225439242',
    projectId: 'shoebot-cd8ad',
    storageBucket: 'shoebot-cd8ad.appspot.com',
    androidClientId: '1095225439242-co4vkk3ra8bf5m0b89gm9iqnk6ka0dsg.apps.googleusercontent.com',
    iosClientId: '1095225439242-lvuuhdso7oprd86n2i70sdd36u3ce12v.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoebot.RunnerTests',
  );
}
